-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 16:17:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pets` ;

-- -----------------------------------------------------
-- Schema pets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pets` DEFAULT CHARACTER SET utf8 ;
USE `pets` ;

-- -----------------------------------------------------
-- Table `pets`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pets`.`table1` ;

CREATE TABLE IF NOT EXISTS `pets`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pets`.`pets` ;

CREATE TABLE IF NOT EXISTS `pets`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(28) NULL,
  `type` VARCHAR(28) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
